### ISSUE TITLE
Pass schema as expression when including templates

### ISSUE THREAD

**Issue by PhilippSalvisberg** [osalvador/tePLSQL#12]
Hello Oscar,

I'd like to replace the schema name in a call like `<%@ include(where_clause, TEPLSQL2_ONE_TO_ONE_VIEW, PACKAGE_BODY, DEMO) %>` with an expression such as
- `$$PLSQL_UNIT_OWNER`
- `SYS_CONTEXT ('USERENV', 'CURRENT_USER')`
- `${schema_name}`

The reason is that I do not know in which schema the users like to install the templates and generators.

Right now avoiding includes and using functions/procedures instead seams to be the best option.

Thank you.

Regards,
Philipp

**Comment by MikeKutz** [comment]
Philipp,
My fork has your enhancement.  I need to test it though.

The third method is the one that was implemented.
ie   ${schema_name}

MK
