### ISSUE TITLE
error when runing into ORA-4068

### ISSUE THREAD

**Issue by MikeKutz** [osalvador/tePLSQL#15]
If you are creating a template that uses a package's interface (cursor,function,procedure,etc.) and that package changes, template creation fails.

**Comment by osalvador** [comment]
Hello MikeKutz,

tePLSQL has no dependencies with other packages and templates are dynamically processed, so the ORA-4068 error should not occur.

Please send me an example to reproduce this bug.

**Comment by MikeKutz** [comment]
I'll try and post a full test script tonight.

General Steps.
1. create a package
2. create a template that uses package (eg   l_template := 'This code uses Package mypkg version <%= mypkg.version() %>'; )
3. render code

everything works.
1. in a 2nd session, modify package so that ora-4084 can occur
2. in 1st session, render code.

result shows error

**Comment by PhilippSalvisberg** [comment]
You could handle this in the template engine, but I think it is OK to delegate the responsibility to handle these kind of errors to the application using the template engine. Responsible for the error is the person/application deploying a stateful  package. The consequences should be known. Re-establishing the states might need more than a simple retry (not in this case).

See also the excellent blog post https://markhoxey.wordpress.com/2013/09/17/avoiding-ora-04068-existing-state-of-packages-has-been-discarded/ to handle/avoid this error. 

I do not consider this a bug.

**Comment by MikeKutz** [comment]
Philipp,
I see your point.

As I think about it, I come to believe that this should be a rare event.
This is based on the philosophy of: the packages used to create a template should be stable.

I seem to be running into this error because I am developing the package and templates in tandem.
(template 1 creates package X which is used by template 2+)

Should I handle the error within my "oddgen generator" or should I have you enhance the oddgen plugin?

**Comment by PhilippSalvisberg** [comment]
> Should I handle the error within my "oddgen generator" or should I have you enhance the oddgen plugin?

Neither of them. You should not experience an ORA-4068 in oddgen for SQL Developer, even if issue oddgen/oddgen#6 was related. However, if this error is really annoying you then it is probably the best to handle it there.

**Comment by MikeKutz** [comment]
I can live with it.
I'm only running into it because of how I am doing development work.

workaround: re-render the code.

note: teplsql.pkb lines 701 & 726 are the lines responsible for catching this error via WHEN OTHERS (without RAISE).

**Comment by osalvador** [comment]
Hi MikeKutz,

The goal of catch exceptions at this point is to return the processed template before being compiled so it can be debugged more easily.

I have overloaded the render function to return the error description and added a RAISE in the WHEN OTHERS.

Thanks for your help both.
