### ISSUE TITLE
q: howto convey what I'm working on?

### ISSUE THREAD

**Issue by MikeKutz** [osalvador/tePLSQL#16]
OK, so I made a fork.
What would be the best way to convey what I'm working on?

Right now, I'm just refactoring the code to allow it to be easier to implement possible future enhancements. eg template/include parameters should accept JSON on 12c+

There are a ton of areas that can be refactored.
Do you want 1 pull request at the end? or 1 pull request per "area refactored"?

MK

**Comment by osalvador** [comment]
Hi Mike,

First, thanks for your contribution.

I think it's better a pull request per refactored area, so we can discuss the refactored code more easily.

regards!

**Comment by MikeKutz** [comment]
It would probably be best if I described "the problem" before I posted the solution.
ie create an issue.

I'll just do the ones involved with this first pull request, for now.

MK

**Comment by osalvador** [comment]
Hi Mike,

I've merged your pull request. Thanks, great contribution .

I have renamed the functions get_code_\* by get_template_\* I seem more correct. I also formatted the code and removed some unnecessary comments.

Again thanks for your contribution
