### ISSUE TITLE
ORA-06503 for get_template_by_table

### ISSUE THREAD

**Issue by MikeKutz** [osalvador/tePLSQL#22]
The exception for NO_DATA_FOUND does not call RETURN.

**Comment by osalvador** [comment]
Hi Mike ,

You mean the line 149 right?

https://github.com/osalvador/tePLSQL/blob/master/tePLSQL.pkb#L149

**Comment by MikeKutz** [comment]
yes.  Line 149.

The compiler for 12c should be able to detect those types of bugs (and others) when you compile with all errors/warnings enabled.

I don't have access to a 12c environment to test.

MK

**Comment by osalvador** [comment]
Hi Mike ,

Thanks. Like you, I don't have access to a 12c environment. 

I'll fix the bug soon.
