### ISSUE TITLE
Could you please provide a release?

### ISSUE THREAD

**Issue by MaikMichel** [osalvador/tePLSQL#39]
Hi,
first of all: thank you for your amazing job. I really like you template engine.
I want to be able to download the latest release by just using curl. So I would be able to check your latest release here:
https://api.github.com/repos/osalvador/tePLSQL/releases/latest and download a zip file.

thank you

**Comment by MikeKutz** [comment]
The `master` branch *is* the latest.  I would just pull it from GitHub directly with this URL:

https://github.com/osalvador/tePLSQL/archive/master.zip

If you have a need for the suggested URL, please explain further.

Thanks,

MK

**Comment by jgebal** [comment]
@MikeKutz 
you should make releases on github
you can put release notes in it.
it allows users to reference specific version they are using.
currently you don't have any release published. 

![SmartSelect_20200804-122438_Brave](https://user-images.githubusercontent.com/1398171/89288530-b6726e80-d64d-11ea-8ca4-c4494b2b59b1.jpg)

**Comment by MaikMichel** [comment]
I have to agree with @jgebal 
And you know, if the user refers to a specific version, if the bug has already been fixed

**Comment by jgebal** [comment]
We use releases with github for utPLSQL.
It's pretty easy to do manually.

**Comment by MikeKutz** [comment]
done.
Let me know if I should do anything else (or if I should just close this Issue)

thanks,

MK
